enum NotificationType {
	FRIEND_REQUEST = 'FRIEND_REQUEST',
	CHAT_MESSAGE = 'CHAT_MESSAGE',
	FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
	USER_STATUS_CHANGED = 'USER_STATUS_CHANGED',
	DIRECT_MESSAGE_REQUEST = 'DIRECT_MESSAGE_REQUEST',
	DIRECT_MESSAGING_DELETED = 'DIRECT_MESSAGING_DELETED',
}

export default NotificationType;